services:
  neo-flowoff-pwa:
    build: .
    ports:
      - "3001:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
